baseURL: http://localhost:1313/acme/
languageCode: es-es 
title: Acme Corporation 
theme: MyTheme 

author: 
  facebook: "https://facebook.com/acme" 
  twitter: "https://twitter.com/acme" 
  email: "contact@acme.com" 
  name: "Acme Corporation" 
  location: Zaragoza
  phone: (999) 999-9999 
  hours: "**Lunes-Viernes** 9:00AM - 6:00PM" 

params: 
  color: "#4f46e5"
  copyright: "Copyright ©; 2022 Acme Corporation. Todos los derechos reservados."
  footer:
  - title: Sobre nosotros
    content: >
      Empresa dedicada a la producción de utensilios de cocina en **papel reciclado**. 


  - title: Publicaciones recientes
    recents: blog
    recentCount: 7

  - title: Contáctanos
    contact: true

  